server:
  port: 8080

spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: restapi_route
          uri: lb://RESTAPI
          predicates:
            - Path=/restapi/**
          filters:
            - StripPrefix=1

        - id: restapi-api-docs
          uri: lb://RESTAPI
          predicates:
            - Path=/v3/api-docs/**
        - id: restapi-swagger-config
          uri: lb://RESTAPI
          predicates:
            - Path=/v3/api-docs/swagger-config

springdoc:
  swagger-ui:
    urls:
      - name: RESTAPI
        url: /restapi/v3/api-docs

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.netflix: DEBUG