server:
  port: 8080

spring:
  application:
    name: GATEWAY

  cloud:
    gateway:
      routes:
        - id: restapi_route
          uri: lb://RESTAPI
          predicates:
            - Path=/restapi/**
          filters:
            - StripPrefix=1
        - id: restapi-api-docs
          uri: lb://RESTAPI
          predicates:
            - Path=/v3/api-docs/**
        - id: restapi-swagger-config
          uri: lb://RESTAPI
          predicates:
            - Path=/v3/api-docs/swagger-config
        - id: restapi-swagger-ui-html
          uri: lb://RESTAPI
          predicates:
            - Path=/swagger-ui.html
        - id: restapi-swagger-ui-resources
          uri: lb://RESTAPI
          predicates:
            - Path=/swagger-ui/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka
  instance:
    preferIpAddress: true