server:
  port: 8080
spring:
  application:
    name: RESTAPI
  datasource:
    url: jdbc:postgresql://postgres:5432/pedido_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50 # Exemplo: 20 conexões máximas por instância do restapi
      minimum-idle: 5       # Exemplo: 5 conexões ociosas mínimas
      connection-timeout: 30000 # 30 segundos (tempo limite para obter uma conexão)
      idle-timeout: 600000    # 10 minutos (tempo limite para conexões ociosas)
      max-lifetime: 1800000   # 30 minutos (tempo máximo de vida de uma conexão)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /restapi/v3/api-docs/swagger-config
    url: /restapi/v3/api-docs
eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
  instance:
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    show-details: "always"

logging:
  level:
    org.springframework.cloud.netflix: DEBUG