server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    hostname: gateway

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: sgp
          uri: lb://sgp
          predicates:
            - Path=/api/orders/**, /api/partners/**
          filters:
            - StripPrefix=1